//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/charactor/input/PlayerControll.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace CharactorController
{
    public partial class @PlayerControll: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerControll()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControll"",
    ""maps"": [
        {
            ""name"": ""PlayerLocalMotionMap"",
            ""id"": ""52111e48-c5fe-43eb-98a6-cbd70afe6519"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""0bb936e2-523e-46f8-bca1-0e0e6e01db60"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""4adb45b9-f832-4c3b-96f5-73f263552338"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""9b48c01f-a9f3-40c5-900e-9f5e0e724ce1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrowModifier"",
                    ""type"": ""Button"",
                    ""id"": ""5467a7b7-99b4-4ccb-a25b-705892cf4c61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""31d86e47-055e-4c9a-becb-417dafe77f3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""d76fc033-a286-4d0d-ac2a-9c1d9f52c2d6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a22af169-bf17-479d-a31c-c2cc6e8973ad"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9de6f1de-f55f-45b0-8c95-7d6c919ec327"",
                    ""path"": ""<AndroidJoystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""43160533-1cf1-4b04-9fa7-08e37e750ddd"",
                    ""path"": ""<NimbusGamepadHid>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b8ff3ac9-7e55-4c39-8ba4-38c9ba36ee57"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4ffaf9b2-cc5f-4ed2-bed4-28ec3eba2dac"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fc500d7-9866-4e94-836f-aeea63482e1f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d40131cb-0bb2-4b2e-8af4-5ff4413458ca"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d026d71a-d7fc-45ec-99f3-e9dcf6457a5f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // PlayerLocalMotionMap
            m_PlayerLocalMotionMap = asset.FindActionMap("PlayerLocalMotionMap", throwIfNotFound: true);
            m_PlayerLocalMotionMap_Movement = m_PlayerLocalMotionMap.FindAction("Movement", throwIfNotFound: true);
            m_PlayerLocalMotionMap_Look = m_PlayerLocalMotionMap.FindAction("Look", throwIfNotFound: true);
            m_PlayerLocalMotionMap_Sprint = m_PlayerLocalMotionMap.FindAction("Sprint", throwIfNotFound: true);
            m_PlayerLocalMotionMap_ThrowModifier = m_PlayerLocalMotionMap.FindAction("ThrowModifier", throwIfNotFound: true);
            m_PlayerLocalMotionMap_Throw = m_PlayerLocalMotionMap.FindAction("Throw", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // PlayerLocalMotionMap
        private readonly InputActionMap m_PlayerLocalMotionMap;
        private List<IPlayerLocalMotionMapActions> m_PlayerLocalMotionMapActionsCallbackInterfaces = new List<IPlayerLocalMotionMapActions>();
        private readonly InputAction m_PlayerLocalMotionMap_Movement;
        private readonly InputAction m_PlayerLocalMotionMap_Look;
        private readonly InputAction m_PlayerLocalMotionMap_Sprint;
        private readonly InputAction m_PlayerLocalMotionMap_ThrowModifier;
        private readonly InputAction m_PlayerLocalMotionMap_Throw;
        public struct PlayerLocalMotionMapActions
        {
            private @PlayerControll m_Wrapper;
            public PlayerLocalMotionMapActions(@PlayerControll wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_PlayerLocalMotionMap_Movement;
            public InputAction @Look => m_Wrapper.m_PlayerLocalMotionMap_Look;
            public InputAction @Sprint => m_Wrapper.m_PlayerLocalMotionMap_Sprint;
            public InputAction @ThrowModifier => m_Wrapper.m_PlayerLocalMotionMap_ThrowModifier;
            public InputAction @Throw => m_Wrapper.m_PlayerLocalMotionMap_Throw;
            public InputActionMap Get() { return m_Wrapper.m_PlayerLocalMotionMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerLocalMotionMapActions set) { return set.Get(); }
            public void AddCallbacks(IPlayerLocalMotionMapActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerLocalMotionMapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerLocalMotionMapActionsCallbackInterfaces.Add(instance);
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @ThrowModifier.started += instance.OnThrowModifier;
                @ThrowModifier.performed += instance.OnThrowModifier;
                @ThrowModifier.canceled += instance.OnThrowModifier;
                @Throw.started += instance.OnThrow;
                @Throw.performed += instance.OnThrow;
                @Throw.canceled += instance.OnThrow;
            }

            private void UnregisterCallbacks(IPlayerLocalMotionMapActions instance)
            {
                @Movement.started -= instance.OnMovement;
                @Movement.performed -= instance.OnMovement;
                @Movement.canceled -= instance.OnMovement;
                @Look.started -= instance.OnLook;
                @Look.performed -= instance.OnLook;
                @Look.canceled -= instance.OnLook;
                @Sprint.started -= instance.OnSprint;
                @Sprint.performed -= instance.OnSprint;
                @Sprint.canceled -= instance.OnSprint;
                @ThrowModifier.started -= instance.OnThrowModifier;
                @ThrowModifier.performed -= instance.OnThrowModifier;
                @ThrowModifier.canceled -= instance.OnThrowModifier;
                @Throw.started -= instance.OnThrow;
                @Throw.performed -= instance.OnThrow;
                @Throw.canceled -= instance.OnThrow;
            }

            public void RemoveCallbacks(IPlayerLocalMotionMapActions instance)
            {
                if (m_Wrapper.m_PlayerLocalMotionMapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayerLocalMotionMapActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerLocalMotionMapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PlayerLocalMotionMapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PlayerLocalMotionMapActions @PlayerLocalMotionMap => new PlayerLocalMotionMapActions(this);
        public interface IPlayerLocalMotionMapActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnSprint(InputAction.CallbackContext context);
            void OnThrowModifier(InputAction.CallbackContext context);
            void OnThrow(InputAction.CallbackContext context);
        }
    }
}
